name: dl_stack

networks:
  starr:
    external: true
  qbit:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:5.1.0-r0-ls397
    container_name: prowlarr
    environment:
      - PUID=${PUID:?error}
      - PGID=${PGID:?error}
      - TZ=${TZ:?error}
    volumes:
      - ${APPDATA:?error}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped 
    networks:
      - starr
      - qbit
      
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID:?error}
      - PGID=${PGID:?error}
      - TZ=${TZ:?error}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${APPDATA}/qbittorrent/config:/config
      - ${SHARE}/torrents:/torrents #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
        - qbit

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      - LANG=en_GB
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
        - qbit
